#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\CacheFactory;
use App\Commands\AnalizeCommand;
use App\Commands\CacheForgetCommand;
use App\Commands\CacheGetCommand;
use App\Commands\CachePutCommand;
use App\Commands\HealtCommand;
use App\Commands\HelpCommand;
use App\Commands\ServicesCacheWarmCommand;
use App\Commands\ServicesCommand;
use App\Commands\VisitCommand;
use App\Commands\VisitorDetailsCommand;
use App\Commands\VisitorDetailsExportCommand;
use App\PCare;
use Dotenv\Dotenv;
use GuzzleHttp\Client;

require_once __DIR__ . '/vendor/autoload.php';

// load environment variables
Dotenv::createImmutable(__DIR__)->load();

// load configuration
$config = new App\Configuration(require __DIR__ . '/config/app.php');

// cache provider
$cache = CacheFactory::create($config, __DIR__);

// create PCare instance
$client_configs = $config->get('client.clients');
$clients        = array_map(fn (array $opt) => new Client($opt), $client_configs);

$pcare = new PCare(
    clients: $clients,
    failureThreshold: $config->get('client.threshold', 3),
    cooldownSeconds: $config->get('client.cooldown', 60),
);

$copy_argv = $argv ?? ['cli', 'help'];
array_shift($copy_argv);
$option = array_shift($copy_argv);

$services = match ($option) {
    // main command
    'service:visit'   => VisitCommand::class,
    'service:detail'  => ServicesCommand::class,
    'service:analize' => AnalizeCommand::class,
    // analize commnad
    'visit:detail'    => VisitorDetailsCommand::class,
    'visit:export'    => VisitorDetailsExportCommand::class,
    // other
    'cache:forget'       => CacheForgetCommand::class,
    'cache:get'          => CacheGetCommand::class,
    'cache:put'          => CachePutCommand::class,
    'cache:service:warm' => ServicesCacheWarmCommand::class,
    // maintenance
    'healt'              => HealtCommand::class,
    default              => HelpCommand::class,
};

/** @var App\Commands\Command */
$app = new $services($argv, __DIR__, $cache, $pcare);

if ($app instanceof VisitorDetailsCommand) {
    $app->setProvider(
        provider: $config->get('bpjs.provider', '')
    );
}

$exit = $app->__main();

exit($exit);
